spring.application.name=DockerProject

spring.datasource.url=mongodb://localhost:27017/dockerdb
spring.data.mongodb.database=dockerdb
spring.data.mongodb.username=
spring.data.mongodb.password=

server.port=8080

